import { Property, NewsArticle, Testimonial, TeamMember } from '@/types';

export const properties: Property[] = [
    {
        id: '1',
        title: 'Ranca Asri Terrace',
        slug: 'ranca-asri-terrace',
        type: 'house',
        price: 850000000,
        location: 'Bandung, West Java',
        bedrooms: 3,
        bathrooms: 2,
        area: 120,
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        featured: true,
        description: 'Modern minimalist house with smart home system in a strategic location near the city center.',
        amenities: ['Smart Home', 'Garden', 'Carport', 'Security 24/7'],
    },
    {
        id: '2',
        title: 'Green Valley Residence',
        slug: 'green-valley-residence',
        type: 'house',
        price: 1200000000,
        location: 'Depok, West Java',
        bedrooms: 4,
        bathrooms: 3,
        area: 180,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        featured: true,
        description: 'Spacious family home with beautiful garden views and premium finishes throughout.',
        amenities: ['Swimming Pool', 'Garden', 'Double Garage', 'Maid Room'],
    },
    {
        id: '3',
        title: 'Crown Jewel Penthouse',
        slug: 'crown-jewel-penthouse',
        type: 'apartment',
        price: 3500000000,
        location: 'Jakarta Selatan',
        bedrooms: 3,
        bathrooms: 2,
        area: 200,
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
        featured: true,
        description: 'Luxury penthouse with panoramic city views and world-class amenities.',
        amenities: ['City View', 'Gym Access', 'Concierge', 'Private Elevator'],
    },
    {
        id: '4',
        title: 'Sunset Villa Bali',
        slug: 'sunset-villa-bali',
        type: 'villa',
        price: 5500000000,
        location: 'Seminyak, Bali',
        bedrooms: 5,
        bathrooms: 4,
        area: 350,
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
        featured: false,
        description: 'Stunning beachfront villa with infinity pool and traditional Balinese architecture.',
        amenities: ['Infinity Pool', 'Beach Access', 'Staff Quarters', 'Pavilion'],
    },
    {
        id: '5',
        title: 'Metropolitan Suites',
        slug: 'metropolitan-suites',
        type: 'apartment',
        price: 1800000000,
        location: 'BSD City, Tangerang',
        bedrooms: 2,
        bathrooms: 2,
        area: 95,
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        featured: false,
        description: 'Modern apartment in the heart of BSD City with complete facilities.',
        amenities: ['Gym', 'Swimming Pool', 'Co-working Space', 'Rooftop Garden'],
    },
    {
        id: '6',
        title: 'Harmony Heights',
        slug: 'harmony-heights',
        type: 'house',
        price: 950000000,
        location: 'Bogor, West Java',
        bedrooms: 3,
        bathrooms: 2,
        area: 140,
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        featured: false,
        description: 'Contemporary home surrounded by nature with cool mountain air.',
        amenities: ['Mountain View', 'Garden', 'BBQ Area', 'Guest House'],
    },
    {
        id: '7',
        title: 'Azure Bay Villa',
        slug: 'azure-bay-villa',
        type: 'villa',
        price: 4200000000,
        location: 'Lombok, NTB',
        bedrooms: 4,
        bathrooms: 3,
        area: 280,
        image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
        featured: false,
        description: 'Exclusive beachfront villa with private beach access and stunning ocean views.',
        amenities: ['Private Beach', 'Pool', 'Outdoor Kitchen', 'Boat Dock'],
    },
    {
        id: '8',
        title: 'Urban Loft Jakarta',
        slug: 'urban-loft-jakarta',
        type: 'apartment',
        price: 2200000000,
        location: 'Menteng, Jakarta',
        bedrooms: 2,
        bathrooms: 1,
        area: 110,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        featured: false,
        description: 'Industrial-style loft apartment in prestigious Menteng area.',
        amenities: ['High Ceiling', 'Gym Access', 'Parking', 'Security 24/7'],
    },
];

export const news: NewsArticle[] = [
    {
        id: '1',
        title: 'Grand Launching Ranca Asri Terrace',
        slug: 'grand-launching-ranca-asri-terrace',
        excerpt: 'Join us for the exclusive grand launching event of our newest residential project.',
        content: 'We are excited to announce the grand launching of Ranca Asri Terrace...',
        image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
        author: 'AsriDev Team',
        publishedAt: '2026-01-15',
        category: 'Event',
    },
    {
        id: '2',
        title: 'Tips for First-Time Home Buyers in 2026',
        slug: 'tips-first-time-home-buyers-2026',
        excerpt: 'Essential guide for navigating the property market as a first-time buyer.',
        content: 'Buying your first home is an exciting milestone...',
        image: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=800&q=80',
        author: 'Property Expert',
        publishedAt: '2026-01-10',
        category: 'Tips',
    },
    {
        id: '3',
        title: 'Sustainable Housing: The Future of Real Estate',
        slug: 'sustainable-housing-future-real-estate',
        excerpt: 'How eco-friendly features are becoming standard in modern homes.',
        content: 'The real estate industry is embracing sustainability...',
        image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80',
        author: 'Green Living',
        publishedAt: '2026-01-05',
        category: 'Insights',
    },
];

export const testimonials: Testimonial[] = [
    {
        id: '1',
        name: 'Budi Santoso',
        role: 'Business Owner',
        company: 'PT Maju Bersama',
        content: 'AsriDev exceeded our expectations. The quality of construction and attention to detail is remarkable. Our family is now living in our dream home.',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
        rating: 5,
    },
    {
        id: '2',
        name: 'Sarah Wijaya',
        role: 'Doctor',
        company: 'RS Premier',
        content: 'Professional service from start to finish. The team was responsive and helpful throughout the entire buying process.',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
        rating: 5,
    },
    {
        id: '3',
        name: 'Ahmad Rahman',
        role: 'IT Director',
        company: 'Tech Solutions',
        content: 'Invested in Green Valley Residence and couldn\'t be happier. The smart home features and build quality are top-notch.',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
        rating: 5,
    },
];

export const teamMembers: TeamMember[] = [
    {
        id: '1',
        name: 'Ir. Andi Pratama',
        role: 'Founder & CEO',
        image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
        bio: 'With over 25 years of experience in real estate development, Andi has led numerous landmark projects across Indonesia.',
        social: {
            linkedin: 'https://linkedin.com/in/andipratama',
            email: 'andi@asridev.com',
        },
    },
    {
        id: '2',
        name: 'Dr. Maya Susanti',
        role: 'Chief Operations Officer',
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
        bio: 'Maya brings strategic vision and operational excellence to AsriDev with her background in business management.',
        social: {
            linkedin: 'https://linkedin.com/in/mayasusanti',
            email: 'maya@asridev.com',
        },
    },
    {
        id: '3',
        name: 'Reza Firmansyah, ST',
        role: 'Head of Architecture',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
        bio: 'Award-winning architect known for innovative designs that blend modern aesthetics with functional living spaces.',
        social: {
            linkedin: 'https://linkedin.com/in/rezafirmansyah',
            email: 'reza@asridev.com',
        },
    },
    {
        id: '4',
        name: 'Linda Kurniawan',
        role: 'Head of Sales & Marketing',
        image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
        bio: 'Linda leads our sales team with a customer-first approach, ensuring every client finds their perfect home.',
        social: {
            linkedin: 'https://linkedin.com/in/lindakurniawan',
            email: 'linda@asridev.com',
        },
    },
];
